title: CreditTools.org
description: CreditTools.org is a not-for-profit website that aims to educate individuals on good credit card and other financial habits. It aims to be the definitive free resource on credit cards.
theme: just-the-docs

permalink: pretty

url: https://credittools.org

aux_links:
  Propose Change: https://github.com/CreditTools/CreditTools.org

aux_links_new_tab: true

collections:
  cards:
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "tests" collection
    cards:
      # Give the collection a name
      name: Cards
      # Exclude the collection from the navigation
      # Supports true or false (default)
      nav_exclude: true
      # Fold the collection in the navigation
      # Supports true or false (default)
      # nav_fold: true  # note: this option is new in v0.4
      # Exclude the collection from the search
      # Supports true or false (default)
      search_exclude: false

plugins:
  - jekyll-default-layout
  - jekyll-seo-tag

# Optional callouts. To use: {: .warning } before paragraph
callouts:
  warning:
    title: Warning
    color: red
  friendly:
    color: blue

# This is needed to format the cards pages
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "_cards"
      type: "cards"
    values:
      layout: "default"

heading_anchors: true
search_enabled: true

footer_content: "Copyright &copy; CreditTools.org"
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/CreditTools/CreditTools.org" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false